version: "3.5"

services:
  authentication_service:
    build: .
    environment:
      - ALGORITHM=HS256
      - SECRET_KEY=SECRET_11111
      - SECRET_KEY_REFRESH=SECRET_222222
      - EXPIRED_TIME_ACCESS_TOKEN=60
      - EXPIRED_TIME_REFRESH_TOKEN=30
    command: uvicorn app.main:api --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./static:/static
    ports:
    - "8000:8000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    ports:
      - "8081:8081"
