version: "3.5"

services:
  authentication_service:
    build: .
    environment:
      - ALGORITHM=HS256
      - SECRET_KEY=SECRET_11111
      - SECRET_KEY_REFRESH=SECRET_222222
      - EXPIRED_TIME_ACCESS_TOKEN=60
      - EXPIRED_TIME_REFRESH_TOKEN=30
    command: uvicorn app.main:api --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
      - ./static:/static
    ports:
      - "8001:8001"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    ports:
      - "8089:8089"
    depends_on:
      - authentication_service
    networks:
      - backend


networks:
  backend:
    name: nginx_auth_network